items = [
    'shampoo',
    'multivitamin',
    'tooth brush',
    'tooth paste',
    'floss',
    't-shirt',
    'jeans',
    'socks',
    'shoes',
    'water bottle',
    'conditioner',
    'body wash',
    'notebook',
    'pen',
    'pencil',
    'sweater',
    'jacket',
    'seltzer',
    'coffee',
    'creamer',
    'bananas',
    'speakers',
    'headphones',
    'laptop',
    'novel',
    'video game',
    'keyboard',
    'guitar',
    'picture frame',
    'chair'
]
